{
	"data": "ENC[AES256_GCM,data:1EWHZXG2gke2PV5q53r2K9MK5SMW8LK1KmAe+GmK4K+slo8A6tcqounixgkhcX5p0s3xmdRmjQeIlNHSp6f6Bg==,iv:R/Rx5bsIZn0sJ4QrUgLQwL/kluT+3XrUpk98Z3h2Vzw=,tag:wCDtqhHG5t4ckAHNkyPnHg==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": null,
		"lastmodified": "2021-11-29T09:09:13Z",
		"mac": "ENC[AES256_GCM,data:bsqftoNQx1FD9SV6YuhvNkNpgPpiGBQ0f+Gb7YDm7WGAakfeNyp1dtOjVVLF18r53wui056e3l6n+C7KHeJTMCCeeSCQgkV3NuyJ8n0/PzfbJ//fTIYf9xueUOCySaniAzeInfXla46OOeKrfIg7645jjcnjdUYqVaF4+K4BtS4=,iv:asUftZYtAPGM5zqa3FKw4A38uiMGn357OftwVkbhsGc=,tag:M51Vyv7gzn8fwmZsDWckkw==,type:str]",
		"pgp": [
			{
				"created_at": "2021-11-29T09:09:12Z",
				"enc": "-----BEGIN PGP MESSAGE-----\n\nhF4DdHEw7A3piNwSAQdA40fYlyOeDolB2hIGvs8puwiyeK8aaspKnv29qx0V5Eow\nz5JJsbNYgF7aJQZZ0p+9St1EbyAkUgAAE0sJxxguKA3TdRh7e99IpvGsd1Hlpl7x\n1GYBCQIQNGt5VLsVRCnsNRc3rv2vs6KuVNfHNVtbFVLivM1JKI1vxzYtlx6daihJ\nAmzX6byEHWwhxobp5PKMwxO3FGdtMys4etdjgzFtLldgePjXHjNRLGTLAWFJyKyJ\nFhhgZxhtvgw=\n=+Nv+\n-----END PGP MESSAGE-----\n",
				"fp": "C1B34A541C6B4F9ABFAE72E4794C2E7D74EA4138"
			}
		],
		"unencrypted_suffix": "_unencrypted",
		"version": "3.7.1"
	}
}